language: go

go:
- 1.8

before_deploy:
- go build
- export SFS_VERSION=`cat VERSION`
- cat simple-file-server | gzip > sfs-$SFS_VERSION.gz

deploy:
  provider: releases
  api_key:
    secure: mM0ErBoQ4O8l0cwlAadG4YlNo+3lqkIaRkTXXBp33Q/OWBcMPeb3phjZuTw4N2/EzeZe+P8MDq9c80GIjcdF1ZQebQeKkpGj6BzCWMFxf3MjOrVA9lfJJRPZa7ZDQicC3PqsR4mEYJllTSwxd2QUqYezE8X2fZypRCYKY1tJwVh3NRmD9yZNSLpEOl2niYCRtFS9+pqGdL0ZpX3pH3pIOeErkdecrrc63rfq2fY8dsQ/9fP0a8rVtLzifIn1GxK99+e5Co/9NfX38b7CgDEPDadQyVpKRGPMskeUhbZQmryCPq0+XWht10Hvhjl+Y6JdarEDaNcnBfCqpGrnEgcTcjSbK3Z0dee0Z5OoCyxAPGj0JGq/faOTwNde64pngHY9P+l8Hvx8Qr/EXFtPPhC/zBIMFaBUQKhI/Y47Guhx2AUwr7yzrPmVzrVYDCIkLU/XtkdcJYif5yZHU/P+YCAtLeHUTJWMxiUg+R331UAkH3i9uidihjtXIhqonfw2TfEwp0kJ0eBBdjn0rEBhok98b7vENF7TRwC+U1fIwHfvMqF9JOtjJoMMLbjSK8KIqlJ00G4/dSIMrIBV1dh0kBU+CHyspbu5QvnC8HNkZjQ0MsGWOrlgbvVL033RV9Six1ZNCZjXycOBaE7Tdwb8ajaXZYT0vaYrqhbl0FIZGt7/H8o=
  file: sfs-$SFS_VERSION.gz
  skip_cleanup: true
  on:
    repo: localghost/simple-file-server
    go: 1.8
    tags: true
